# -*- mode: ruby -*-
# vi: set ft=ruby :

$yum_script = <<EOF
yum update -y
EOF

$postgresql_script = <<EOF
yum -y localinstall https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
yum -y install postgresql10-server
/usr/pgsql-10/bin/postgres --version
/usr/pgsql-10/bin/postgresql-10-setup initdb
EOF

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.define :db1 do |db1|
    db1.vm.network "private_network", ip: "192.168.33.10"
    db1.vm.provision "shell", inline: $yum_script
    db1.vm.provision "shell", inline: $postgresql_script    
  end
  config.vm.define :db2 do |db2|
    db2.vm.network "private_network", ip: "192.168.33.11"
    db2.vm.provision "shell", inline: $yum_script
    db2.vm.provision "shell", inline: $postgresql_script
  end
  config.vm.define :db3 do |db3|
    db3.vm.network "private_network", ip: "192.168.33.12"
    db3.vm.provision "shell", inline: $yum_script
    db3.vm.provision "shell", inline: $postgresql_script
  end
end
